CrudFinal/Models/ContatoModel.cs
using System.ComponentModel.DataAnnotations;

namespace CrudFinal.Models
{
    public class ContatoModel
    {

        public int Id { get; set; }
        [Required(ErrorMessage ="Digite o Nome")]
        public string Nome { get; set; }
        [Required(ErrorMessage ="Digite o RG")]
        public string Rg { get; set; }
        [Required(ErrorMessage ="Digite o cpf")]
        public string Cpf { get; set; }
        [Required(ErrorMessage ="Digite o E-mail")]
        [EmailAddress(ErrorMessage ="Digite um E-mail Valido")]
        public string Email { get; set; }
        [Required (ErrorMessage ="Digite o celular do Contato")]
        [Phone(ErrorMessage ="Digite um telefone valido")]
        public string Celular { get; set; }
        [Required(ErrorMessage ="Digite o Cep")]
        public string Cep { get; set; }
        [Required(ErrorMessage ="Digite cidade")]
        public string Cidade { get; set; }
        [Required(ErrorMessage ="Informe o Sexo")]
        public string Sexo { get; set; }
      
       
        
        public DateTime Data { get; set; }
        
        }
}

CrudFinal/Models/ErrorViewModel.cs
namespace CrudFinal.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CrudFinal/Controllers/ApiPessoaController.cs
using CrudFinal.ModelsApi;
using CrudFinal.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.ComponentModel;
using System.Diagnostics.Contracts;
using System.Reflection.Metadata.Ecma335;
using System.Security.Policy;
using System.Text;

namespace CrudFinal.Controllers
{


    public class ApiPessoaController : Controller
    {
        string _apiPessoa = "https://localhost:7021/Pessoa";

        private readonly IUsuario _IUsuario;
        public ApiPessoaController(IUsuario IUsuario)
        {
            _IUsuario = IUsuario;
        }
        
        public IActionResult Index()
        {
            return View(_IUsuario.BuscartodasPessoas());   
        }

        public IActionResult Criar(PessoaApiModel collection)
        {
            _IUsuario.Cadastrar(collection);
            

            



            return View(collection); 
        }

    }
}

CrudFinal/Controllers/ContatoController.cs
using CrudFinal.Models;
using CrudFinal.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace CrudFinal.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _ContatoRepositorio;
        public ContatoController(IContatoRepositorio ContatoRepositorio)
        {

            _ContatoRepositorio = ContatoRepositorio;
        }
        public IActionResult Index()
        {
            var contato = _ContatoRepositorio.BuscarTodos();
            return View(contato);
        }


        public IActionResult Adicionar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _ContatoRepositorio.Listarporid(id);
            return View(contato);
        }

        public IActionResult ConfirmarExclusao(int id)
        {
            ContatoModel contato = _ContatoRepositorio.Listarporid(id);
            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            _ContatoRepositorio.Apagar(id);
            return RedirectToAction("index");
        }
        [HttpPost]
        public IActionResult Adicionar(ContatoModel contato)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (_ContatoRepositorio.BuscarEmail(contato)) {
                        TempData["UsuarioExisteEmail"] = "E-MAIL JÁ CADASTRADO";
                        return View(contato);
                        
                           
                    }

                     if (_ContatoRepositorio.BuscarCpf(contato))
                    {
                        TempData["UsuarioExisteCpf"] = "CPF JÁ CADASTRADO";
                        return View(contato);
                    }

                    _ContatoRepositorio.Adicionar(contato);
                    TempData["MensagemSucesso"] = "Contato Cadastrado com Sucesso";
                    return RedirectToAction("Index");
                }
                return View(contato);
            }

            catch (System.Exception erro)
            {
                TempData["MensagemErro"] = $"Ops,não conseguimos cadastrar seu contato ,tente novamente, detalhe do erro:{erro.Message}";
                return RedirectToAction("index");
            }

        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            _ContatoRepositorio.Atualizar(contato);
            return RedirectToAction("Index");
        }
    }
}

CrudFinal/Controllers/HomeController.cs
using CrudFinal.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CrudFinal.Controllers
{
    public class HomeController : Controller
    {

        public IActionResult Index()
        {
            return View();
        }

        
    }
}

CrudFinal/Views/ApiPessoa/Criar.cshtml
@model CrudFinal.ModelsApi.PessoaApiModel

@{
    ViewData["Title"] = "Criar";
}

<h1>Criar</h1>

<h4>PessoaApiModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Criar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sobrenome" class="control-label"></label>
                <input asp-for="Sobrenome" class="form-control" />
                <span asp-validation-for="Sobrenome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CrudFinal/Views/ApiPessoa/Index.cshtml
@model IEnumerable<CrudFinal.ModelsApi.PessoaApiModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Criar">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sobrenome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sobrenome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

CrudFinal/Views/Contato/Adicionar.cshtml
@model ContatoModel

@{
    ViewData["Title"] = "Adicionar";
}

<h1>Cadastrar</h1>

@if (TempData["UsuarioExisteEmail"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["UsuarioExisteEmail"]
    </div>
}
@if (TempData["UsuarioExisteCpf"] != null)

{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["UsuarioExisteCpf"]
    </div>
}

<form class="row"asp-controller="Contato" asp-action="Adicionar" method="post">
    <div class="row">
    <div class="col-md-4">
        <label for="Nome" class="form-label">Nome</label>
        <input type="text"asp-for="Nome" class="form-control" id="inputnome">
        @Html.ValidationMessageFor(x=>x.Nome)
    </div>
    <div class="col-md-4">
        <label for="RG" class="form-label">RG</label>
        <input type="text"asp-for="Rg" class="form-control" id="inputrg">
         @Html.ValidationMessageFor(x=>x.Rg)
    </div>
    <div class="col-md-4">
        <label for="CPF" class="form-label">CPF</label>
        <input type="text" asp-for="Cpf" class="form-control" id="inputcpf" placeholder="000.000.000-00">
            @Html.ValidationMessageFor(x=>x.Cpf)
    </div>
    
    
    <div class="col-md-4">
        <label for="E-mail" class="form-label">E-mail</label>
        <input type="text" asp-for="Email" class="form-control" id="inputemail" placeholder="email@email.com">
            @Html.ValidationMessageFor(x=>x.Email)
    </div>
    <div class="col-md-4">
        <label for="Celular" class="form-label">Celular</label>
            <input type="text" asp-for="Celular" class="form-control" id="inputcelular" placeholder="(00)00000-0000">
            @Html.ValidationMessageFor(x=>x.Celular)
    </div>
    <div class="col-md-4">
        <label for="Cep" class="form-label">Cep</label>
        <input type="text" asp-for="Cep" class="form-control" id="inputcep">
            @Html.ValidationMessageFor(x=>x.Cep)
    </div>
    
    
    <div class="col-md-4">
        <label for="Cidade" class="form-label">Cidade</label>
        <input type="text" asp-for="Cidade" class="form-control" id="inputcidade">
            @Html.ValidationMessageFor(x=>x.Cidade)
    </div>
    <div class="col-md-4">
        <label for="Sexo" class="form-label">Sexo</label>
        <select id="inputSexo" asp-for="Sexo" class="form-control">
         <option selected>Sexo</option>
        <option>Masculino</option>
        <option>Feminino</option>
        </select>
            @Html.ValidationMessageFor(x=>x.Sexo)
     </div>
    <div class="col-md-4">
            <label for="Data Nascimento" class="form-label">Data Nascimento</label>
        <input type="date" asp-for="Data" class="form-control">
            @Html.ValidationMessageFor(x=>x.Data)
    </div>
    </div>
       <div class="col-md-4">
           <br />
                <button type="submit" class="btn btn-primary" class="bg-light border">Confirmar</button>
        <a role="button" class="btn btn-danger" asp-route-id="" asp-controller="Contato" asp-action="Index"> Cancelar</a>
    </div>  
    


</form>

CrudFinal/Views/Contato/ConfirmarExclusao.cshtml
@model ContatoModel

<h3>Tem certeza que deseja excluir @Model.Nome </h3>

<a role="button" class="btn btn-danger" asp-route-id="@Model.Id" asp-controller="Contato" asp-action="Apagar">Apagar</a>
<a role="button" class="btn btn-primary"  asp-controller="Contato" asp-action="Index"> Cancelar</a>

CrudFinal/Views/Contato/Editar.cshtml
@model ContatoModel
<h1>Editar</h1>




<form class="row" asp-controller="Contato" asp-action="Alterar" method="post">
   <input type="hidden" asp-for="Id" />
    
    <div class="row">
        <div class="col-md-4">
            <label for="Nome" class="form-label">Nome</label>
            <input type="text" asp-for="Nome" class="form-control" id="inputnome">
        </div>
        <div class="col-md-4">
            <label for="RG" class="form-label">RG</label>
            <input type="text" asp-for="Rg" class="form-control" id="inputrg">
        </div>
        <div class="col-md-4">
            <label for="CPF" class="form-label">CPF</label>
            <input type="text" asp-for="Cpf" class="form-control" id="inputcpf" placeholder="000.000.000-00">
        </div>


        <div class="col-md-4">
            <label for="E-mail" class="form-label">E-mail</label>
            <input type="text" asp-for="Email" class="form-control" id="inputemail" placeholder="email@email.com">
        </div>
        <div class="col-md-4">
            <label for="Celular" class="form-label">Celular</label>
            <input type="text" asp-for="Celular" class="form-control" id="inputcelular" placeholder="(00)00000-0000">
        </div>
        <div class="col-md-4">
            <label for="Cep" class="form-label">Cep</label>
            <input type="text" asp-for="Cep" class="form-control" id="inputcep">
        </div>


        <div class="col-md-4">
            <label for="Cidade" class="form-label">Cidade</label>
            <input type="text" asp-for="Cidade" class="form-control" id="inputcidade">
        </div>
        <div class="col-md-4">
            <label for="Sexo" class="form-label">Sexo</label>
            <select id="inputSexo" asp-for="Sexo" class="form-control">
                <option selected>Sexo</option>
                <option>Masculino</option>
                <option>Feminino</option>
            </select>
        </div>
        <div class="col-md-4">
            <label for="Data Nascimento" class="form-label">Data Nascimento</label>
            <input type="date" asp-for="Data" class="form-control">

        </div>
    </div>
    <div class="col-md-4">
        <br />
        <button type="submit" class="btn btn-primary" class="bg-light border">Confirmar</button>
        <a role="button" class="btn btn-danger" asp-route-id="" asp-controller="Contato" asp-action="Index"> Cancelar</a>
    </div>



</form>

CrudFinal/Views/Contato/Index.cshtml
@model List<ContatoModel>



<a type="button" class="btn btn-primary" asp-controller="Contato" asp-action="Adicionar">Adicionar  </a>
<div id="topindex">
    
</div>

@if(TempData["MensagemSucesso"]!=null){
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger" role="alert">
        <button type="button" class="btn btn-danger btn-sm close-alert" arial-label="Close">X</button>
        @TempData["MensagemErro"]
    </div>
}

<table class="table" id="tabelacontato">
    <thead>
        <tr>
            <th scope="col">Nome</th>
            <th scope="col">RG</th>
            <th scope="col">CPF</th>
            <th scope="col">E-mail</th>
            <th scope="col">Celular</th>
            <th scope="col">CEP</th>
            <th scope="col">Cidade</th>
            <th scope="col">Sexo</th>
            <th scope="col">Data</th>
            <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null && Model.Any()){

            foreach (var item in Model)
            {
                <tr>
                    <th scope="row">@item.Nome</th>
                    <td>@item.Rg</td>
                    <td>@item.Cpf</td>
                    <td>@item.Email</td>
                    <td>@item.Celular</td>
                    <td>@item.Cep</td>
                    <td>@item.Cidade</td>
                    <td>@item.Sexo</td>
                    <td>@item.Data</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a role="button" class="btn btn-primary" asp-route-id="@item.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                            <a role="button" class="btn btn-danger" asp-route-id="@item.Id" asp-controller="Contato" asp-action="ConfirmarExclusao"> Apagar</a>
                        </div>
                    </td>
                </tr>

            }
        }

       
    </tbody>
</table>

CrudFinal/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/imagen1.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>First slide label</h5>
                <p>Some representative placeholder content for the first slide.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/imagem2.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Second slide label</h5>
                <p>Some representative placeholder content for the second slide.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/imagem3.jpg" class="d-block w-100" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Third slide label</h5>
                <p>Some representative placeholder content for the third slide.</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

CrudFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CrudFinal</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudFinal.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.css" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CrudFinal</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="index">Cadastro</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ApiPessoa" asp-action="Index">API PESSOA</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CrudFinal - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.16/jquery.mask.min.js" integrity="sha512-pHVGpX7F/27yZ0ISY+VVjyULApbDlD0/X0rgGbTqCE7WFW5MezNTWG/dnhtbBuICzsd0WQPgpE4REBLv+UqChw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.13.1/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>